name: workflow test
on:
  push:
    branches: [ main ]
  workflow_call:
    inputs:
      backendDisable:
        required: false
        type: boolean
        default: false
      frontendDisable:
        required: false
        type: boolean
        default: false
      e2eDisable:
        required: false
        type: boolean
        default: false
      e2eSimulateFailure:
        required: false
        type: boolean
        default: false

jobs:
  Setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'

  BackendBuild:
    name: Backend build
    if: inputs.backendDisable  == false
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'

  FrontendBuild:
    name: Backend build
    if: inputs.frontendDisable  == false
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'

  IntegrationTest:
    if: (inputs.e2eDisable == false) && always()
    needs: [  BackendBuild, FrontendBuild]
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
    - run: |
        [[ "${{ inputs.e2eSimulateFailure }}" = true ]] && exit 1
      shell: bash
        
  Frontend-build-and-push-image:
    name: Frontend Build and Push Container
    if: (inputs.frontendDisable == false) && !failure()
    needs: [IntegrationTest]
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'

  Backend-build-and-push-image:
    name: Backend Build and Push Container
    if: inputs.backendDisable == false && !failure()
    needs: [IntegrationTest]
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'